all: 	
	javac -cp ../include/ *.java
	java -cp .:../include/ Shard -config configuration.json

clean:	
	rm *.class

remove:
	rm dwane_wade.*
	rm kobe.*
	rm vince_carter.*
	rm michael_jordan.*
	rm -rf metaData.json